import { Kalam, Great_Vibes } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const kalam = Kalam({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-kalam",
});

const greatVibes = Great_Vibes({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-great-vibes",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${kalam.variable} ${greatVibes.variable}`}>
      <body className={`font-kalam antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
